import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * 🗃️ Data export module
 * Id: cdecab39-0c0c-4316-b5c5-759b4d8946a1
 * Codename: _data_export_module
 */
export type __DataExportModule = IContentItem<{
    /**
     * Export data (custom)
     * Required: false
     * Id: e0f7abc4-8449-4fc5-8975-bf7ab7b8b074
     * Codename: export_data
     */
    exportData: Elements.CustomElement;
}>;
