import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * ⌨ CKeditor
 * Id: c8472d91-051c-4997-a704-517603065e84
 * Codename: __ckeditor
 */
export type _CKeditor = IContentItem<{
    /**
     * CKeditor (custom)
     * Required: false
     * Id: 9bccbed4-ffb9-4df7-af2c-182280cb9930
     * Codename: ckeditor
     */
    ckeditor: Elements.CustomElement;
}>;
