import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * 🎨 Layout settings
 * Id: 65dc2cf5-4994-40f6-8eb7-f0eec4ed23ce
 * Codename: _layout_settings
 */
export type _LayoutSettings = IContentItem<{
    /**
     * Brand Choice (custom)
     * Required: true
     * Id: 6a7cd243-e41e-4898-b8ef-2b86e635a777
     * Codename: brand_choice
     */
    brandChoice: Elements.CustomElement;
}>;
