import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Banner
 * Id: 1074f8fc-9ca8-43bd-af5d-bf970ec500df
 * Codename: banner
 */
export type Banner = IContentItem<{
    /**
     * Image (asset)
     * Required: false
     * Id: 4b9575e7-31aa-4528-879f-c4e54a6ea580
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Title (text)
     * Required: false
     * Id: cf4a2b67-eae0-4557-a74d-bddb0462f330
     * Codename: title
     */
    title: Elements.TextElement;
}>;
