import { type IContentItem } from '@kontent-ai/delivery-sdk';
import { type BrandCTA } from '../content-type-snippets/brandCTA';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Brand CTA
 * Id: 93a85abd-096e-4913-957f-9ce470519d4d
 * Codename: brand_cta_93a85ab
 */
export type BrandCTA = IContentItem<{}> & BrandCTA;
