import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type HeadingTags } from './headingTags';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Card and U Classes
 * Id: 99a3717c-257a-4a59-beef-5610335a4e5e
 * Codename: card_and_u_classes
 */
export type CardAndUClasses = IContentItem<{
    /**
     * Button Classes (text)
     * Required: false
     * Id: ea27b89c-fee3-43b3-99d8-b51a32bd83dd
     * Codename: button_classes
     */
    buttonClasses: Elements.TextElement;

    /**
     * Button Link URL (text)
     * Required: false
     * Id: be756d98-7f6a-4e8f-893e-3ac2574a827c
     * Codename: button_link_url
     */
    buttonLinkUrl: Elements.TextElement;

    /**
     * Button Text (text)
     * Required: false
     * Id: eb114538-8ac7-49f6-8b47-4b19d7b4737b
     * Codename: button_text
     */
    buttonText: Elements.TextElement;

    /**
     * Description (text)
     * Required: false
     * Id: 65db48f2-29d8-4cbf-9d8e-ecc96a34bbee
     * Codename: description
     */
    description: Elements.TextElement;

    /**
     * Description Classes (text)
     * Required: false
     * Id: 114f9f2c-0def-4f43-a2a5-eff0ebb13b9c
     * Codename: description_classes
     */
    descriptionClasses: Elements.TextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 8ea0db9b-64eb-4382-9c65-b836fbeacb3a
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Image Classes (text)
     * Required: false
     * Id: 34edbc71-daeb-4f3e-adab-d22c15cab308
     * Codename: image_classes
     */
    imageClasses: Elements.TextElement;

    /**
     * Title (text)
     * Required: false
     * Id: e12d3c38-b1f0-4393-8db1-489486e7c23a
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * Title Classes (text)
     * Required: false
     * Id: ffdc01ef-4dad-4caf-9c09-149ca2000cc1
     * Codename: title_classes
     */
    titleClasses: Elements.TextElement;

    /**
     * Heading Tags (modular_content)
     * Required: false
     * Id: 4da0c061-70ec-4d9e-9006-ee6991dcbe6f
     * Codename: untitled_linked_items
     */
    untitledLinkedItems: Elements.LinkedItemsElement<HeadingTags>;
}>;
