import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type BrandCTA } from '../content-type-snippets/brandCTA';
import { type CTACard } from './CTACard';
import { type SEOHeading } from '../content-type-snippets/SEOHeading';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * CTA Cards
 * Id: 794fa506-3932-42eb-8a68-5fd7359a762f
 * Codename: cta_cards
 */
export type CTACards = IContentItem<{
    /**
     * Cards (modular_content)
     * Required: true
     * Id: 82e8404a-a019-4702-b1a6-e0e8b217c228
     * Codename: cards
     */
    cards: Elements.LinkedItemsElement<CTACard>;

    /**
     * Description (rich_text)
     * Required: true
     * Id: 8189eb49-782d-4b57-8340-12f12cc41d9e
     * Codename: description
     */
    description: Elements.RichTextElement;
}> &
    BrandCTA &
    SEOHeading;
