import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type BrandCTA } from '../content-type-snippets/brandCTA';
import { type SEOHeading } from '../content-type-snippets/SEOHeading';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * CTA Card
 * Id: e7392e9c-486a-4578-acae-6fefdbfe2e06
 * Codename: cta_card
 */
export type CTACard = IContentItem<{
    /**
     * Description (text)
     * Required: false
     * Id: 9c1d1b71-5b65-4d29-a6ca-1b2eeb0c4b8b
     * Codename: description
     */
    description: Elements.TextElement;

    /**
     * Image (asset)
     * Required: true
     * Id: 943a3f7c-90de-454b-8e2a-17635732919b
     * Codename: image
     */
    image: Elements.AssetsElement;
}> &
    BrandCTA &
    SEOHeading;
