import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Embedded code
 * Id: bf590046-c791-4f9a-8085-d8f010f40595
 * Codename: embedded_code
 */
export type EmbeddedCode = IContentItem<{
    /**
     * Code (text)
     * Required: false
     * Id: 49d7fe64-79d7-4e13-a83f-c89247605acc
     * Codename: code
     */
    code: Elements.TextElement;
}>;
