import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Form
 * Id: 3c42c40d-468a-439a-8a4f-9f3ce7ee0bae
 * Codename: form_3c42c40
 */
export type Form = IContentItem<{
    /**
     * Email (text)
     * Required: false
     * Id: 4e64f17b-7071-4c2d-b80d-718c5584b7eb
     * Codename: email
     */
    email: Elements.TextElement;

    /**
     * First Name (text)
     * Required: false
     * Id: 942203ce-ab3f-405a-8459-be99cc070d25
     * Codename: first_name
     */
    firstName: Elements.TextElement;

    /**
     * Google ID (text)
     * Required: false
     * Id: 425dfbfa-d724-4fc6-bd9c-e9db01e7f3d5
     * Codename: google_id
     */
    googleId: Elements.TextElement;

    /**
     * Last Name (text)
     * Required: false
     * Id: b8c718ac-a732-42a7-a142-402b51d4ae71
     * Codename: last_name
     */
    lastName: Elements.TextElement;

    /**
     * Phone (text)
     * Required: false
     * Id: 46cb744f-8f12-4ad9-b5bf-312d15438ff4
     * Codename: phone
     */
    phone: Elements.TextElement;
}>;
