import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type LayoutOption } from '../content-type-snippets/layoutOption';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Grid Component
 * Id: 38f329b7-75bd-4645-932a-f8a9b83db086
 * Codename: grid_component
 */
export type GridComponent = IContentItem<{
    /**
     * Columns (number)
     * Required: true
     * Id: b99c755a-a29b-4cfd-853c-6e10973f74ad
     * Codename: columns
     */
    columns: Elements.NumberElement;

    /**
     * Content (rich_text)
     * Required: false
     * Id: d4572956-d630-4aca-affd-86a675508e4e
     * Codename: content
     */
    content: Elements.RichTextElement;
}> &
    LayoutOption;
