import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Heading Tags
 * Id: f19d353f-17ec-42d8-9ae7-f7f5b5a6b03c
 * Codename: heading_tags
 */
export type HeadingTags = IContentItem<{
    /**
     * Heading Tag (text)
     * Required: false
     * Id: 6dee3765-2a37-4f78-a81c-7a72cba18555
     * Codename: heading_tag
     */
    headingTag: Elements.TextElement;
}>;
