import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CallToAction } from './callToAction';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Hero Unit (copy)
 * Id: e916f914-1212-4095-a1b5-8ab5c3ef49ce
 * Codename: hero_unit__copy_
 */
export type HeroUnitCopy = IContentItem<{
    /**
     * Background image (asset)
     * Required: false
     * Id: f766227c-b34d-4345-ac49-9d9f1764092c
     * Codename: background_image
     */
    backgroundImage: Elements.AssetsElement;

    /**
     * Call to Action (modular_content)
     * Required: false
     * Id: e05c08df-7c2f-49be-b99a-718ac6df7170
     * Codename: call_to_action
     */
    callToAction: Elements.LinkedItemsElement<CallToAction>;

    /**
     * Content (rich_text)
     * Required: false
     * Id: 5bcd9261-33a4-4bc6-9d63-aa95e9480836
     * Codename: content
     */
    content: Elements.RichTextElement;

    /**
     * Eyebrow Text (text)
     * Required: false
     * Id: c1ba85c7-87a6-49b7-af63-ece40574a4ad
     * Codename: eyebrow_text
     */
    eyebrowText: Elements.TextElement;

    /**
     * Title (text)
     * Required: false
     * Id: 53a9c7f3-5ea9-4087-96f8-8cf0f2b6a8dd
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * UTM Tag (text)
     * Required: false
     * Id: 6f59afc0-d19a-461c-879b-467f9b701b4b
     * Codename: utm_tag
     */
    utmTag: Elements.TextElement;
}>;
