import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Image
 * Id: 08e3b976-fa17-416d-9738-5ae73f73d4e0
 * Codename: image
 */
export type Image = IContentItem<{
    /**
     * Author of image (text)
     * Required: false
     * Id: 5f944eb0-db8c-411b-9884-601b7623807a
     * Codename: author_of_image
     */
    authorOfImage: Elements.TextElement;

    /**
     * Image/Asset (asset)
     * Required: false
     * Id: 67605334-7b04-486a-8ab4-941592244347
     * Codename: image_asset
     */
    imageAsset: Elements.AssetsElement;

    /**
     * Override mobile image (asset)
     * Required: false
     * Id: 80f63927-9e91-454d-a9b9-89a5d9d9743f
     * Codename: override_mobile_image
     */
    overrideMobileImage: Elements.AssetsElement;
}>;
