import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Integration with Bynder (DAM)
 * Id: 7ba8a6b8-0383-4fb2-8259-86f3a8e907ed
 * Codename: integration_with_bynder__dam_
 */
export type IntegrationWithBynderDAM = IContentItem<{
    /**
     * Image from Bynder (custom)
     * Required: false
     * Id: 55c62b68-7590-4c06-94bf-beb2c5b02102
     * Codename: image_from_bynder
     */
    imageFromBynder: Elements.CustomElement;
}>;
