import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CallToAction } from './callToAction';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Panel
 * Id: cd495da0-4247-4456-8d83-288a777f6c23
 * Codename: _panel
 */
export type Panel = IContentItem<{
    /**
     * Content (text)
     * Required: false
     * Id: 972b7b5b-348d-4983-be0b-084f53bd8f6a
     * Codename: blurb
     */
    blurb: Elements.TextElement;

    /**
     * CTA (modular_content)
     * Required: false
     * Id: 07efcc05-71f8-4c1c-892b-7200cd76445a
     * Codename: cta
     */
    cta: Elements.LinkedItemsElement<CallToAction>;

    /**
     * Heading (text)
     * Required: false
     * Id: 83ec6bbc-0271-416b-9dad-188c825b39a9
     * Codename: heading
     */
    heading: Elements.TextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 0c947609-33fc-49d4-8d89-fea08403a503
     * Codename: image
     */
    image: Elements.AssetsElement;
}>;
