import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Rich Text Area
 * Id: 6185661e-6113-4d32-badb-9d3741461374
 * Codename: rich_text_area
 */
export type RichTextArea = IContentItem<{
    /**
     * Untitled rich text (rich_text)
     * Required: false
     * Id: 4192f72c-d949-4151-8ab6-e8f82cd9c723
     * Codename: untitled_rich_text
     */
    untitledRichText: Elements.RichTextElement;
}>;
