import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Channels } from '../taxonomies/channels';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Site Layout Options
 * Id: 11b840be-02c2-486f-86c8-4619539d01c2
 * Codename: site_layout_options
 */
export type SiteLayoutOptions = IContentItem<{
    /**
     * Channels (taxonomy)
     * Required: false
     * Id: 1ff2d971-91e3-49d9-8b8e-426f12b991b7
     * Codename: channels
     */
    channels: Elements.TaxonomyElement<Channels>;

    /**
     * Color Scheme (multiple_choice)
     * Required: false
     * Id: e07f0636-64fc-4d38-b25a-15daa6cf8b10
     * Codename: color_scheme
     */
    colorScheme: Elements.MultipleChoiceElement;

    /**
     * Hide (multiple_choice)
     * Required: false
     * Id: 38db2157-4de4-45f9-a9e7-b703bed28719
     * Codename: hide
     */
    hide: Elements.MultipleChoiceElement;
}>;
