import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type LayoutOption } from '../content-type-snippets/layoutOption';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Tab Component
 * Id: e2960526-654a-4d26-bf81-2833eadddd0b
 * Codename: tab_component
 */
export type TabComponent = IContentItem<{
    /**
     * Tabs (number)
     * Required: true
     * Id: 3b5ba1e8-e0aa-4477-aec5-8df1b4fbd770
     * Codename: columns
     */
    columns: Elements.NumberElement;

    /**
     * Content (rich_text)
     * Required: false
     * Id: 3536c507-2c4f-4409-80fd-260576971bbf
     * Codename: content
     */
    content: Elements.RichTextElement;
}> &
    LayoutOption;
