/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Personas
 * Id: cc0dab16-2c55-44c8-a377-99edc7096bca
 * Codename: personas
 */
export type Personas =
    | 'the_budget_conscious_buyer'
    | 'the_eco_conscious_innovator'
    | 'the_industry_expert'
    | 'the_practical_professional'
    | 'the_trendsetter';
