import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Brand CTA
 * Id: 9f66a3d6-95bc-4914-84ba-0aacf47ac718
 * Codename: brand_cta
 */
export type BrandCTA = IContentItem<{
    /**
     * Link (modular_content)
     * Required: false
     * Id: b2bc146e-698f-4f02-a868-7cf2f445cdc2
     * Codename: brand_cta__link
     */
    brandCtaLink: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Style (custom)
     * Required: false
     * Id: 037f6f6b-a514-4f07-8f9a-cb0d2a373d7a
     * Codename: brand_cta__style
     */
    brandCtaStyle: Elements.CustomElement;
}>;
