import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type WSL_Page } from '../content-types/WSL_Page';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Brand CTA
 * Id: 9f66a3d6-95bc-4914-84ba-0aacf47ac718
 * Codename: brand_cta
 */
export type BrandCTA = IContentItem<{
    /**
     * Link (modular_content)
     * Required: false
     * Id: 8c0bce55-3b6b-46eb-92fc-867d53fd814e
     * Codename: brand_cta__link
     */
    brandCtaLink: Elements.LinkedItemsElement<WSL_Page>;

    /**
     * Style (custom)
     * Required: false
     * Id: deb9bf5d-3feb-427e-9676-e185c7c0f4fa
     * Codename: brand_cta__style
     */
    brandCtaStyle: Elements.CustomElement;
}>;
