import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Brand CTA
 * Id: 9f66a3d6-95bc-4914-84ba-0aacf47ac718
 * Codename: brand_cta
 */
export type BrandCTA = IContentItem<{}>;
