import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * SEO Heading
 * Id: 4fd429a2-b1c9-472b-b6b7-e11481b8a15b
 * Codename: heading_options
 */
export type SEOHeading = IContentItem<{
    /**
     * Heading Level (custom)
     * Required: false
     * Id: d6812058-9606-485f-ab19-5525385a73c1
     * Codename: heading_options__heading_level
     */
    headingOptionsHeadingLevel: Elements.CustomElement;

    /**
     * Title (text)
     * Required: false
     * Id: 417c2d69-a484-4735-9e34-617407786f1b
     * Codename: heading_options__title
     */
    headingOptionsTitle: Elements.TextElement;
}>;
