/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const collections = {
    /**
     * City Index
     */
    site_b: {
        codename: 'site_b',
        id: '9d2b67c9-e5d3-48cc-a84f-27937dd7a0b7',
        name: 'City Index'
    },

    /**
     * Component Library
     */
    component_library: {
        codename: 'component_library',
        id: '062be9e1-1355-4dea-82b7-64acbbcfd07d',
        name: 'Component Library'
    },

    /**
     * Configuration
     */
    configuration: {
        codename: 'configuration',
        id: 'd6ebf81b-a49b-4a19-8093-10b027698c27',
        name: 'Configuration'
    },

    /**
     * Forex
     */
    site_a: {
        codename: 'site_a',
        id: '4508189b-9565-43a4-9405-fff5d56c0a68',
        name: 'Forex'
    },

    /**
     * Global and Shared Content
     */
    default: {
        codename: 'default',
        id: '00000000-0000-0000-0000-000000000000',
        name: 'Global and Shared Content'
    },

    /**
     * Mr  Fusion Marketing Campaign
     */
    mr_fusion_marketing_campaign: {
        codename: 'mr_fusion_marketing_campaign',
        id: '278d733b-c22f-4598-ba31-e3ebde41d1c6',
        name: 'Mr. Fusion Marketing Campaign'
    },

    /**
     * StoneX
     */
    sandbox: {
        codename: 'sandbox',
        id: '3905681f-dce2-4a90-8dab-425d4b73ea9c',
        name: 'StoneX'
    },

    /**
     * Stonex MMjr
     */
    stonex_mmjr: {
        codename: 'stonex_mmjr',
        id: '8c46bc01-5092-489e-b0f5-fb91b89747e9',
        name: 'Stonex MMjr'
    }
} as const;
