/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const webhooks = {
    /**
     * Automatic Translation
     */
    automaticTranslation: {
        url: 'https://stonex.kontent.dev/api/translate-webhook/',
        id: 'b2631eb5-b933-44b9-a85d-0731e0a2e948',
        name: 'Automatic Translation'
    }
} as const;
